### ISSUE TITLE
Minor typos (do not impact the proper functioning)

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-debian#12]
Bonjour,

quelques typos qui n'impactent pas le fonctionnement, "allready" au lieu de "already" :

https://github.com/cozy/cozy-debian/blob/fd0d982d9a690b9fa2d951994788a04c92cfdc86/debian/postinst#L101

https://github.com/cozy/cozy-debian/blob/fd0d982d9a690b9fa2d951994788a04c92cfdc86/debian/postinst#L109

**Comment by clochix** [comment]
Merci @nicofrand ☺
@nledez va corriger cela.

**Comment by nledez** [comment]
Merci @nicofrand,

C'est corrigé dans e11003834f14a9b0325fb8601236e4f60912ae5f.

Ce sera dans le prochain package Debian.
