### ISSUE TITLE
no sysvinit script for couchdb

### ISSUE THREAD

**Issue by jeekajoo** [cozy/cozy-debian#17]
Hi,

I'm using debian jessie in a LXC.
Official documentation advises to switch back to Sysvinit because of incompatility with systemd: https://wiki.debian.org/LXC#Incompatibility_with_systemd
This is what I did.
But it looks like there is no init script in your couchdb package: https://github.com/nledez/cozy-couchdb-debian. So it won't start and installs fails.. Too bad.
Am I wrong with my observation?

Thanks

**Comment by nledez** [comment]
This issue was moved to cozy/couchdb-debian#1
