### ISSUE TITLE
Test npm version

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#18]
Some users have installed npm manually and encounter problem installing some packages. We should probably check the installed npm version (in the install script or in the diagnose script).

**Comment by frankrousseau** [comment]
I think it would be simpler to move Cozy to Node 4

**Comment by clochix** [comment]
Last week, some user had strange bugs when installing the .deb or updating their apps. It appears that what because they installed npm with npm itself, instead of using the one packaged with Debian. I think we'll still encounter that sort of problem after moving to Node 4, so it's worth adding two line of script to check the version of npm.

**Comment by nledez** [comment]
I think it fixed by 183adc0a671203deda9eac73f5cfd65a7552f001

https://github.com/cozy/cozy-debian/blob/master/debian/cozy-depends.postinst#L25-L35

We can install the package "cozy-depends" before continue installation.

WDYT @clochix?

Can we close the issue?

**Comment by clochix** [comment]
I do think this is definitively great !
Thanks !
