### ISSUE TITLE
Add an auto compact for CouchDB database

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-debian#21]
As discuss with @babolivier we can add auto-compact on CouchDB

**Comment by frankrousseau** [comment]
Thank you @nledez. Can you describe more what this issue is about? It makes the understanding easier for the repository visitor.

**Comment by babolivier** [comment]
@frankrousseau I'll allow myself to explain as we discussed this issue together with @nledez.
Some self-hosted users (a lot of them?) aren't aware of the fact that, in order for the database not to fill all the available disk space with data, you have to compact it frequently. This feature aims to automating this action (via a cron task for example), so Cozy doesn't mess the machine if the user forget to compact the DB, or just doesn't know he has to.

**Comment by aenario** [comment]
What was the reasoning against using couchdb auto compact feature ?

**Comment by nledez** [comment]
It's for the Debian package. Self hosting users can be auto-compacted.

**Comment by clochix** [comment]
Closing, as the Node.js version of Cozy is now deprecated.
