### ISSUE TITLE
PGP key has just expired

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#22]
The key used to sign the package has just expired.
Once updated, we probably also need to update the doc.

**Comment by nledez** [comment]
Key validity is now extend to 2016-11-16.

May be we need to update cozy.io with new fingerprint:
`pub   2048R/2765B235 2014-11-17 [expires: 2016-11-16]
      Key fingerprint = E28C F8B2 ABBF E285 743B  27F1 BCB2 ED5D 2765 B235
uid                  Cozy Debian Packaging <debian-packaging@cozycloud.cc>`

**Comment by clochix** [comment]
Documentation updated in cozy/cozy-docs#207
Thanks @nledez
