### ISSUE TITLE
ucf dependency needed (cozy-apt-node-list.postinst, line 32)

### ISSUE THREAD

**Issue by u1735067** [cozy/cozy-debian#26]
When following https://docs.cozy.io/en/host/install/install-on-debian.html on a fresh debian:8 docker image, `cozy_management install_cozy` fails with `/var/lib/dpkg/info/cozy-apt-node-list.postinst: line 32: ucf: command not found`

**Comment by clochix** [comment]
Thanks for reporting @Alex131089, @nledez will take care of adding the missing dependency to the package ☺

**Comment by nledez** [comment]
Add in be881ffa0530df1849d184d3f2117c997e207dcb.

Thanks
