### ISSUE TITLE
Check NodeJS version

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-debian#3]
If an nodejs already install check version before continue.

**Comment by nledez** [comment]
Version >= 0.10.34

**Comment by nicofrand** [comment]
It did not work with 0.12+ (see https://forum.cozy.io/t/solved-debian-installation-depuis-depot/998/10).
The current default version on Debian Jessie is 0.10.29.

**Comment by nledez** [comment]
Closed with be881ffa0530df1849d184d3f2117c997e207dcb. Could you check it @nicofrand  (when package is released)?

And if it's works for you, closed the issue.

**Comment by nicofrand** [comment]
I will install a debian VM and try this out.

How I plan to do it: install nodejs 0.12 from nodesource.com:

``` console
# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_0.12 | bash -
apt-get install -y nodejs
```

And then install cozy.

**Comment by aenario** [comment]
Cozy will not work with node v0.12.xx. You need to install the highest v0.10.xx

**Comment by frankrousseau** [comment]
@aenario I think @nicofrand wants to check if the package detects well that the node version is wrong.

**Comment by nicofrand** [comment]
Yup that's right (I talked about it with @aenario on IRC ;)).

Le lun. 17 août 2015 19:21, Frank Rousseau notifications@github.com a
écrit :

**Comment by aenario** [comment]
Yep, sorry again for speaking before thinking :)
