### ISSUE TITLE
Debian Testing: install fails because python-software-properties package missing

### ISSUE THREAD

**Issue by clayt0nk** [cozy/cozy-debian#30]
Hi, the python-software-properties package seems to be entirely missing from the Debian archive after Jessie. Therefore on testing/unstable:

The following packages have unmet dependencies:
 cozy-depends : Depends: python-software-properties but it is not installable 
E: Unable to correct problems, you have held broken packages.

And I cannot complete a normal install. Note that new Debian stable comes out later this year, presumably(?) still with this problem. A quick look at

https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=unstable;package=python-software-properties

does not indicate any Release Critical bugs, so I am not sure why it disappeared.

**Comment by clochix** [comment]
Thanks for reporting @clayt0nk,

For the record, we only support Debian Stable channel. But we'll keep an eye on this to get prepared to the release of next stable version.

On Testing, maybe could you try the [python3-software-properties](https://packages.debian.org/stretch/python3-software-properties) package (looks like the package is only available for Python 3 in Testing and Sid.

**Comment by clayt0nk** [comment]
For that to work, the Python bits of Cozy need to be Python3 ready, and your installer needs to know about it, otherwise I cannot finish the install process.

**Comment by nledez** [comment]
Thanks for report @clayt0nk but as said @clochix we support only Jessie & Trusty at this time.
