### ISSUE TITLE
Blocking configure even with pre-config

### ISSUE THREAD

**Issue by aeris** [cozy/cozy-debian#33]
Config script [cozy-standalone.config](https://github.com/cozy/cozy-debian/blob/master/debian/cozy-standalone.config) is always blocking, even if debconf parameters were prefilled (`debconf-set-selections`).

This is problematic for unattended installation (image build) and all settings without user interaction (raspi first boot from official image).

**Comment by clochix** [comment]
Thanks for reporting @aeris,

Who could fix this? You or @nledez ?

**Comment by aeris** [comment]
I’m on it. Problems seems more build environment (systemd, chroot, ...) than this script.

**Comment by clochix** [comment]
Closing, as the Node.js version of Cozy is now deprecated.
