### ISSUE TITLE
Delete cozy-* users when purging

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#35]
We should find a way to delete every users created by Cozy.

**Comment by babolivier** [comment]
We can use this as a base:

```
# cat /etc/passwd | cut -d":" -f1 | grep cozy
```

This lists all users beginning with "cozy".

I tried it on my personnal server (after creating fake "cozy-" accounts), but didn't seem to be able to pipe `userdel` to this command line.

Alternatively, a `for` loop in a bash script should do the trick.

**Comment by nono** [comment]
Maybe with `xargs`:

``` bash
cat /etc/passwd | cut -d":" -f1 | grep cozy | xargs -L1 userdel
```

**Comment by clochix** [comment]
@nono we should use a moar specific regex, like `^cozy\-`.

**Comment by nono** [comment]
@clochix yes, my comment was just an answer to @babolivier to show `xargs`
