### ISSUE TITLE
Create a package for Ubuntu Xenial (16.04)

### ISSUE THREAD

**Issue by sscherfke** [cozy/cozy-debian#37]
The latest LTS of Ubuntu has been released a few months ago.  It would be nice if you could provide a package for xenial (in addition to the one for trusty).

**Comment by clochix** [comment]
Hi @sscherfke 
Supporting Ubuntu 16.04 is definitively on our short term todo list. Unfortunately, we really have a lot of items on this list, so I can't give you an ETA.

**Comment by sscherfke** [comment]
Knowing that it’s on your todo list is enough for the moment. :)

**Comment by sscherfke** [comment]
Any updates on this?

**Comment by jsilvestre** [comment]
Hi @sscherfke,

After I talked to the team, we decided not to push Xenial support in the next few weeks. We have literally tons of things to do, and supporting a new distribution is quite costly, given the current state of the platform (it's not well packaged for many reasons, which make testing time-consuming).

It was not an easy decision to make, and everyone would have preferered to do it, but we have deadline to meet. We will reconsider this at the end of the year.

Sorry,
Joseph.

**Comment by sscherfke** [comment]
Hi @jsilvestre ,
tanks for the update. Although it’s not what I wanted to hear, I can absolutely understand it.
Again, thx for your feedback! :)
Stefan

**Comment by severin-lemaignan** [comment]
Hello! Any update on this front?

**Comment by clochix** [comment]
Hello @severin-lemaignan, thanks for your interest in Cozy ☺
A [major rewriting of Cozy is in progress](https://blog.cozycloud.cc/post/2016/11/21/On-the-road-to-Cozy-version-3). We are migrating the server part from node.js to golang. Once it has been done, in a few month, packaging Cozy should be way easier, and I hope we'll provide packages for newer versions of Ubuntu. But the current version won't be packaged for 16.04.

**Comment by severin-lemaignan** [comment]
ok! thanks for the update!

**Comment by clochix** [comment]
The Node.js version of Cozy is now deprecated.

To learn how to install the new version of Cozy, please refer to our (in progress) [documentation](https://docs.cozy.io/en/).
