### ISSUE TITLE
Install failed - Check NodeJS version

### ISSUE THREAD

**Issue by viki53** [cozy/cozy-debian#4]
Hi, 

I tried yesterday to install Cozy on my personal server (OVH KimSufi with Debian) so I could test Cozy (I'm currently using ownCloud but I'm more of a Node.js kinda guy now — my PHP era is almost over).

But I got the following error message (in French):

``` shell
> apt-get install cozy
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 cozy : Dépend: nodejs mais il n'est pas installable
        Dépend: nodejs-legacy mais il n'est pas installable
        Dépend: npm mais il n'est pas installable
        Dépend: coffeescript mais il n'est pas installable
        Dépend: couchdb mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

So basically some dependencies cannot be installed (even though most of them are already installed, like nodejs and npm).

Any idea what went wrong and how to solve it?

Thanks a lot!

**Comment by nledez** [comment]
Could you give me the response of command?:
`cat /etc/apt/sources.list /etc/apt/sources.list.d/*`

Thanks.

**Comment by nledez** [comment]
And:

```
dpkg -l node\*
```

**Comment by viki53** [comment]
``` shell
> cat /etc/apt/sources.list /etc/apt/sources.list.d/*

deb http://debian.mirrors.ovh.net/debian/ wheezy main
deb-src http://debian.mirrors.ovh.net/debian/ wheezy main

deb http://security.debian.org/ wheezy/updates main
deb-src http://security.debian.org/ wheezy/updates main
deb http://debian.cozycloud.cc/debian jessie main
deb http://packages.dotdeb.org wheezy-php56 all
deb-src http://packages.dotdeb.org wheezy-php56 all
deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen
deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen
deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/ /

```

``` shell
> dpkg -l node\*
dpkg-query: aucun paquet ne correspond à node*
```

``` shell
> node -v
v0.10.36
```

I think I installed nodejs manually a few months ago, so I may have not done it right…

**Comment by nledez** [comment]
Same issue as #3

Can you give me this command too?

```
dpkg -S $(which node)
```

**Comment by viki53** [comment]
That's weird…

``` shell
$ dpkg -S $(which node)
dpkg-query: aucun chemin ne correspond à /usr/local/bin/node
$ which node
/usr/local/bin/node
```

**Comment by clochix** [comment]
/usr/local/bin/node is probably a symlink, you can try:

```
dpkg -S $(readlink -f `which node`)
```

**Comment by viki53** [comment]
Nope. It's a symlink, but following it doesn't seem to solve the issue…

``` shell
$ which node
/usr/local/bin/node

$ readlink -f `which node`
/opt/node/bin/node

$ dpkg -S $(readlink -f `which node`)
dpkg-query: aucun chemin ne correspond à /opt/node/bin/node
```

I'm not really familiar with Debian (I basically do some `apt-get upgrade` and `npm start` and stuff like that most of the time)

**Comment by nledez** [comment]
How do you installed nodejs? Manually?

**Comment by viki53** [comment]
I'm not really sure, but I think I did it manually, yes.

I've been trying to update it (to v0.12.x) for two days from the package manager, but it doesn't seem to work…

---

[EDIT] Okay, I think I finally managed to remove the old package and install the new one. I'll just check that my current projects still work and I'll try to run Cozy Cloud again

**Comment by nledez** [comment]
One of problems with Debian packaging. If you install a software manualy, it's harder for Debian to deal with this.

May be you need to clean your manual installation before retry a new installation.

Another solution if you are very sure about your installation is to make a dummy package:
http://eric.lubow.org/2010/system-administration/creating-dummy-packages-on-debian/

**Comment by viki53** [comment]
Now that Node.js is properly installed, the message is shorter: 

``` shell
Les paquets suivants contiennent des dépendances non satisfaites :
 cozy : Dépend: coffeescript mais il n'est pas installable
        Dépend: couchdb mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

I tried running some `npm install -g coffescript && npm install -g couchdb`, but this error is still there as these are only npm packages.

Maybe I need to remove some _cached_ files from before?

**Comment by nledez** [comment]
Are you on Debian Jessie with this repository:
http://cozy.io/en/host/install/install-on-debian.html

**Comment by viki53** [comment]
Oops, looks like I'm still on Debian 7.5.

I just read [the update manual (FR)](https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.fr.html) and it looks pretty risky to update without a backup, so I'll have to wait a little until I can clear everything out. Or maybe there's a Cozy version for Debian 7.5?

**Comment by nledez** [comment]
Ok, I understand all your problems now.

There are many way to install cozy. A virtual machine or container on your current host.

Or our fabric cozy-setup:
https://github.com/cozy/cozy-setup

**Comment by nledez** [comment]
Duplicate with #3
