### ISSUE TITLE
Let's encrypt: we need the certificate chain file

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#41]
Users using a Let's Encrypt certificate with Apache need to add a `SSLCertificateChainFile` directive with the chain file:

```
SSLCertificateChainFile "/etc/letsencrypt/…/chain.pem"
```

On Nginx, users should assure to use the fullchain file:

```
ssl_certificate fullchain.pem
```

**Comment by Zeuh** [comment]
`SSLCertificateChainFile `is obsolete since apache 2.4.8 (Debian Stretch : 2.4.25)
https://httpd.apache.org/docs/2.4/fr/mod/mod_ssl.html#sslcertificatechainfile

With Debian Stretch you also used the `fullchain.pem` with `SSLCertificateFile` directive.

**Comment by clochix** [comment]
Thanks @Zeuh 😄 

For the record, this version of Cozy is now deprecated.

Please refer to https://docs.cozy.io/en/install/debian/ for installing the new version of Cozy.

**Comment by Zeuh** [comment]
@clochix : Perhaps adding an header in README.md of the project  ?

**Comment by clochix** [comment]
@Zeuh yes, see #50 
We should decide whether we mark this repository as obsolete of use it for the new Debian packages.
