### ISSUE TITLE
Add support for Let's encrypt with Apache

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#42]
For now, we are only able to use Let's Encrypt to sign the server certificate if the user uses cozy-nginx. We should add LE support into cozy-apache (this may require updating `cozy_management`).

**Comment by nicofrand** [comment]
See https://forum.cozy.io/t/lets-encrypt-https-auto-heberge/1738/11 for the configuration to use.

**Comment by clochix** [comment]
Closing, as the Node.js version of Cozy is now deprecated.
