### ISSUE TITLE
Dependencies conflict with certbot

### ISSUE THREAD

**Issue by masfaraud** [cozy/cozy-debian#43]
Hi,

The installation with `cozy_management install_cozy` fails, in fact  installation of cozy-standalone fails because of dependencies conflict:

```
Les actions suivantes permettront de résoudre ces dépendances :

      Supprimer les paquets suivants :
1)      certbot
2)      python-acme
3)      python-certbot
4)      python-certbot-apache
5)      python-cffi-backend
6)      python-pyasn1

      Réinstaller à une version antérieure les paquets suivants :
7)      python-cffi [1.4.2-2~bpo8+1 (jessie-backports, now) -> 0.8.6-1 (stable)]
8)      python-cryptography [1.3.4-1~bpo8+2 (jessie-backports, now) -> 0.6.1-1 (stable)]
9)      python-openssl [16.0.0-1~bpo8+1 (jessie-backports, now) -> 0.14-1 (stable)]

      Laisser les dépendances suivantes non satisfaites :
10)     python-ndg-httpsclient recommande python-pyasn1
11)     python-urllib3 recommande python-pyasn1
12)     python-requests recommande python-pyasn1

```

It is possible for the .deb to use newer versions of python-cff, python-cryptography and python-openssl to avoid this conflict?

**Comment by clochix** [comment]
Thanks for reporting @masfaraud

**Comment by neurovertex** [comment]
No fix or workaround for this ?

**Comment by clochix** [comment]
Hello @neurovertex,

We are aware of a compatibility issue between certbot and Cozy. I think you need to remove certbot to be able to install Cozy. Cozy use another Let's Encrypt client, [Acme Tiny](https://github.com/diafygi/acme-tiny).

**Comment by clochix** [comment]
The Node.js version of Cozy is now deprecated.

To learn how to install the new version of Cozy, please refer to our (in progress) [documentation](https://docs.cozy.io/en/).
