### ISSUE TITLE
Improve CouchDB admin deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-debian#44]
The `reset_token` action require the couchdb user and password from `/etc/cozy/couchdb.login`. But if this file is lost or wrong, user has no way to drop CouchDB admin.
We should add some sort of hard delete that delete admin from CouchDB configuration and restart the server.
The best way to do this that I have found is:

```
for n in {1..10}; do sed -i -e '/^\[admins\]/{n;d}' /etc/couchdb/local.ini; done;
service couchdb restart
```

**Comment by jsilvestre** [comment]
You are right, thank you @clochix !

**Comment by clochix** [comment]
Closing, as this version of Cozy is now deprecated.
