### ISSUE TITLE
DigitalOcean install instructions don't work

### ISSUE THREAD

**Issue by jcrben** [cozy/cozy-debian#48]
When I tried to follow the steps at https://docs.cozy.io/en/host/install/install-on-digitalocean.html using Debian 8.6 I get the following error at the `cozy_management install_cozy` step:

![image](https://cloud.githubusercontent.com/assets/5614134/20295949/fa94b34a-aabc-11e6-8ce7-13442bdd30e5.png)

Haven't figured out the fix. Seems that it was designed around 8.1 and 8.6 broke something. 8.1 no longer seems to be available from DigitalOcean for new droplets. Perhaps you should recommend Ubuntu LTS for DigitalOcean, or have some CI running against new Debian versions?

**Comment by jcrben** [comment]
Ended up following the https://docs.cozy.io/en/host/install/install-on-ubuntu.html which seem to work for DigitalOcean - by the way, at one point I was directed to learn about Cozy Mobile and self-signed certificates at https://davdroid.bitfire.at/faq/entry/importing-a-certificate/ but that seems to no longer go to an FAQ item - should have had your own link or an archive link there.

**Comment by clochix** [comment]
The Node.js version of Cozy is now deprecated.

To learn how to install the new version of Cozy, please refer to our (in progress) [documentation](https://docs.cozy.io/en/).
