### ISSUE TITLE
apt-get purge cozy doesn't work if cozy-monitor missing

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-debian#5]
Removing cozy (1.3) ...
/var/lib/dpkg/info/cozy.prerm: 22: /var/lib/dpkg/info/cozy.prerm: cozy-monitor: not found
/var/lib/dpkg/info/cozy.prerm: 24: /var/lib/dpkg/info/cozy.prerm: cozy-monitor: not found
dpkg: error processing package cozy (--purge):
 subprocess installed pre-removal script returned error exit status 127
Errors were encountered while processing:
 cozy
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nledez** [comment]
Fixed in 1.5

**Comment by ebretteville** [comment]
So we have to install it to be able to uninstall it?!
