### ISSUE TITLE
Add a warning about self-signed certificates

### ISSUE THREAD

**Issue by nono** [cozy/cozy-debian#6]
Hi,

I've installed cozy with the debian package. Then, I tried to sync calendar and contacts with my android phone.I didn't see any warning about the self-signed certificate during the process.

There is a warning about it on http://cozy.io/fr/mobile/files.html#a-propos-des-certificats-auto-sign-s. I think it should be copy-pasted on https://cozy.myinstance.cc/#apps/sync/. Or on http://cozy.io/fr/mobile/contacts.html#android and http://cozy.io/fr/mobile/calendar.html#android.

**Comment by nledez** [comment]
Fixed by 36d5e2f639d10f4e20695e49d566550f08821b7e

@nono could you test it and close issue if it's good for you? Thanks.

**Comment by nono** [comment]
Thanks! It's good for me.
