### ISSUE TITLE
auto redirect to https is missing in Apache

### ISSUE THREAD

**Issue by tykayn** [cozy/cozy-debian#7]
after setting up my cozy cloud on a ubuntu 14.04 server with the tutorial on the site,
adding a dns entry (field type A) for my server, i was unable to reach my cozy sub domain.

the https auto redirect wasnt done, it lead to the apache2 default localhost webpage.

then, i accessed the https homepage to register my user, and the form was displayed.
but after filling and checking the fields were valid with the "?" icons, i was unable to send the form.

now i can't access the /register page, or the base page, with or without https.

tihs is the error i get ni chrome:
DNS_PROBE_FINISHED_NXDOMAIN

any idea about this ?

**Comment by frankrousseau** [comment]
Thank you @tykayn for reporting.

@nledez @Kloadut any idea?

**Comment by nledez** [comment]
Hello, @tykayn,

It's because the Apache redirect is missing.

**Comment by nledez** [comment]
Solved by 1.9 36f27a23edfcdb52e33075667432b0ab1b4dd97f

@tykayn, you can test the upgrade . And tell me if it solved your problem?

If yes. Thank's to close the issue.
